stages:
  - publish

covid-stats-x86:
  stage: publish
  script:
    - setsid ./ci/docker-deliver.sh "x86" "covid-stats" "1.4"
  only:
    refs:
      - /^(master.*)$/
    changes:
      - get_stats.sh
      - Dockerfile
  tags:
    - covid19

covid-stats-arm:
  stage: publish
  script:
    - setsid ./ci/docker-deliver.sh "arm" "covid-stats" "1.4"
  only:
    refs:
      - /^(master.*)$/
    changes:
      - get_stats.sh
      - Dockerfile.arm
  tags:
    - buildarm
