version: "3.3"

services:
  covid-stats-x86:
    image: comworkio/covid-stats:1.3-arm
    environment:
      - ELASTIC_URL=http://es01:9200
      - ELASTIC_AUTHENTICATION=disabled
      - STARTUP_WAIT_TIME=60
      - DEBUG_MODE=disabled
    networks:
      - covid19
  es01:
    image: comworkio/elasticsearch:7.9.1-arm
    container_name: es01
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - covid19

networks:
  covid19:
    driver: bridge
