ARG BALENA_DEBIAN_TAG=buster
ARG BALENA_DEBIAN_DIGEST=sha256:b32c2579e735f8257211c9b2c2eeab6db199907e138380833dbe2515cc6878e3

FROM balenalib/raspberrypi3-debian:${BALENA_DEBIAN_TAG}@${BALENA_DEBIAN_DIGEST}

ENV DAEMON_MODE=enabled \
    CONTAINER_MODE=enabled

COPY ./get_stats.sh /

RUN apt-get update -y && \
    apt-get install curl bash jq -y && \
    chmod +x /get_stats.sh

CMD ["/get_stats.sh", "-a"]
