version: "3.3"

services:
  covid-stats:
    image: comworkio/covid-stats:1.5-arm
    environment:
      - ELASTIC_URL=http://es01:9200
      - ELASTIC_AUTHENTICATION=disabled
      - STARTUP_WAIT_TIME=60
      - DEBUG_MODE=disabled
    networks:
      - covid19
  es01:
    image: comworkio/elasticsearch:7.13.2-1.1-arm
    container_name: es01
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - covid19
    volumes:
      - data01:/usr/share/elasticsearch/data
  kib01:
    image: comworkio/kibana:7.13.2-1.7-arm
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      - ES_PROTO=http
      - ES_HOST=es01
      - ES_PORT=9200
    networks:
      - covid19
    depends_on: 
      - es01

volumes:
  data01:
    driver: local

networks:
  covid19:
    driver: bridge
